---
- secret:
    name: SECRET_NODE_IMAGE
    data:
      MINIO_ACCESS_KEY: !encrypted/pkcs1-oaep
        - Xyo9dhgCiURY/SMtKPRtrU89JlYk5cv6Yj5rMfmpyoY5+46BenMvn6diMPJoYlXL4O5tM
          RvfTO/k6xdrSimEjei/Fae82Mr/JFm3nCUULdbc6WedR0jSdZZAUCXoRbSMy3Y0IBsSM+
          rtAOFIosEF0rJtM7Jrm6sOqrGUZRMByn7bDutosRK9XmZeAHaOLSIM49NRWrx5cl3GsIx
          ZW2HHELamjx/divxMjKVQP1N0n0iO9lDRnxYvheOXcbH+iWMnYgmaoGKPQ7MvQhirqgic
          eC6B0f9zCHPoBSYWm1zjASuI+bYc8d1PM5fgtdGYJwE7HPN+nMucXIAqQi+6dZNA5D2y7
          9G56aKm7GpQRzNlTamYML6yWT5FVgtZvOZMktR4Ygb/+CH5HJF8rVne7hhEbsny6c8PzL
          Llq2nDDwaDNc1Ltpq4dI6fShjcvIWmt+48u8FE7qaRuHQG2fugOoHQU0sOVXSf0DAHKhO
          EmlKaCqoL3vxDzWAyA4U5IIrSIv77ED0xSboCI+8qSpguE0s2tkii0iVoRvIAlrmKrUxX
          Ft8sF+WkWwaOLg6gOKo6g3sAhF2fzAbxFcvCCoo3SU0yxaltlnq8eIGJGNfArCvBIwMTZ
          8T1H7p5vyNiGNC7k2/6asZDHnRoOzB1iGOwRP5XD2I3MCSi23ewsuQIofodVzw=
      MINIO_SECRET_KEY: !encrypted/pkcs1-oaep
        - Z+RrUQo4NSHNJTZvG0mMq2BJFQqYV80rlV8xefbGxzcMSm4EDi/t1h0Wak71+buU6F1K5
          nTWROU21DlnAlabHEG7T36bze4mzN+/ccaLCkH8OBBG4WygFjpaHBg8l23DFMWHT4aat5
          21Ij7DwfvHXuS2S3/8qtSAw7G1o2tCY7Os3S1f86c+UB77tvB83+Urbc9Km93b0/MN2LV
          IRqwyccIcXCiYgs0XOotWfRKhW8sGk8rqfvcvT5OUgiHhRIIM/I7PrprD8RfG2YzyJ/9V
          Rx8GpAgLRH6Wfxhh8U3hLzbzUv/G5yvY/T8PDirqeXzfPl+Lnm3pxZlZRkF83rNKo95rX
          CSWgMKwDPS7DoVBs4c0w26FVoQXbVn5NlnqsFgiZC7e5K1q0Sk1JaJIzhLc/YhutvwW5W
          pGJTWedoTWCXk3OJle2d6LKLI6ZBgCPwWNUFQenK9RMmV1NpoQNeSl/ejR8vvq53yJQ53
          DwbgNQGi5sWWfv1PAIatZRShHL63oMbR3+k39isJR1SrDM0eKR8vkYTJn1kvWXOfxTLFG
          Pd4Ut+KfAb/HVWNnCEX0g2IafOrRkynR+Dj0yimEbRX0QTicbUcQmF6w6TudT+D3/ZnrQ
          3CGapx0SBFtugeHkZ0aQnTunC5fym4cdZj+XJqtdhuvvu7/V/wrKgjfIsKp9wE=

- semaphore:
    name: semaphore-node-image-build
    max: 5

- job:
    name: node-image-build
    nodeset: ubuntu-jammy-large
    abstract: true
    semaphores:
      - name: semaphore-node-image-build
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800
    vars:
      upload_image: false

- job:
    name: node-image-build-1
    parent: node-image-build
    vars:
      variant: 1
      description: 'Two mirrored SCSI disks with an enhanced set of predefined logical volumes'

- job:
    name: node-image-build-2
    parent: node-image-build
    vars:
      variant: 2
      description: 'Two mirrored SCSI disks with a single logical rootfs volume'

- job:
    name: node-image-build-3
    parent: node-image-build
    vars:
      variant: 3
      description: 'A single SCSI disk with a single logical rootfs volume'

- job:
    name: node-image-build-4
    parent: node-image-build
    vars:
      variant: 4
      description: 'A single NVMe disk with a single logical rootfs volume (/dev/nvme0n1)'

- job:
    name: node-image-build-cloud-in-a-box-1
    parent: node-image-build
    vars:
      variant: cloud-in-a-box-1
      description: 'A Cloud in a Box image for a single SCSI disk with a single logical rootfs volume'

- job:
    name: node-image-build-cloud-in-a-box-2
    parent: node-image-build
    vars:
      variant: cloud-in-a-box-2
      description: 'A Cloud in a Box image for a single NVMe disk with a single logical rootfs volume'

- job:
    name: node-image-build-cloud-in-a-box-edge-2
    parent: node-image-build
    vars:
      variant: cloud-in-a-box-edge-2
      description: 'A Cloud in a Box edge image for a single NVMe disk with a single logical rootfs volume'

- job:
    name: node-image-build-cloud-in-a-box-kubernetes-1
    parent: node-image-build
    vars:
      variant: cloud-in-a-box-kubernetes-1
      description: 'A Cloud in a Box image with Kubernetes for a single SCSI disk with a single logical rootfs volume'

- job:
    name: node-image-build-cloud-in-a-box-kubernetes-2
    parent: node-image-build
    vars:
      variant: cloud-in-a-box-kubernetes-2
      description: 'A Cloud in a Box image with Kubernetes for a single NVMe disk with a single logical rootfs volume'

- job:
    name: node-image-build-osism-1
    parent: node-image-build
    vars:
      variant: osism-1
      description: 'Two mirrored NVMe disks with a single logical rootfs volume (/dev/nvme3n1 and /dev/nvme4n1)'

- job:
    name: node-image-build-osism-2
    parent: node-image-build
    vars:
      variant: osism-2
      description: 'Two mirrored NVMe disks with a single logical rootfs volume (/dev/nvme4n1 and /dev/nvme5n1)'

- job:
    name: node-image-build-osism-3
    parent: node-image-build
    vars:
      variant: osism-3
      description: 'Two mirrored NVMe disks with a single logical rootfs volume (/dev/nvme2n1 and /dev/nvme3n1)'

- job:
    name: node-image-build-osism-4
    parent: node-image-build
    vars:
      variant: osism-4
      description: 'Two mirrored NVMe disks with a single logical rootfs volume (/dev/nvme0n1 and /dev/nvme1n1)'

- job:
    name: node-image-publish-1
    parent: node-image-build-1
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-2
    parent: node-image-build-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-3
    parent: node-image-build-3
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-4
    parent: node-image-build-4
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-1
    parent: node-image-build-cloud-in-a-box-1
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-2
    parent: node-image-build-cloud-in-a-box-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-edge-2
    parent: node-image-build-cloud-in-a-box-edge-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-kubernetes-1
    parent: node-image-build-cloud-in-a-box-kubernetes-1
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-kubernetes-2
    parent: node-image-build-cloud-in-a-box-kubernetes-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-osism-1
    parent: node-image-build-osism-1
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-osism-2
    parent: node-image-build-osism-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-osism-3
    parent: node-image-build-osism-3
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-osism-4
    parent: node-image-build-osism-4
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - flake8
        - hadolint
        - python-black
        - yamllint
        - node-image-build-1
    label:
      jobs:
        - node-image-build-1
        - node-image-build-2
        - node-image-build-3
        - node-image-build-4
        - node-image-build-cloud-in-a-box-1
        - node-image-build-cloud-in-a-box-2
        - node-image-build-cloud-in-a-box-edge-2
        - node-image-build-cloud-in-a-box-kubernetes-1
        - node-image-build-cloud-in-a-box-kubernetes-2
        - node-image-build-osism-1
        - node-image-build-osism-2
        - node-image-build-osism-3
        - node-image-build-osism-4
    post:
      jobs:
        - node-image-publish-1:
            branches: main
        - node-image-publish-2:
            branches: main
        - node-image-publish-3:
            branches: main
        - node-image-publish-4:
            branches: main
        - node-image-publish-cloud-in-a-box-1:
            branches: main
        - node-image-publish-cloud-in-a-box-2:
            branches: main
        - node-image-publish-cloud-in-a-box-edge-2:
            branches: main
        - node-image-publish-cloud-in-a-box-kubernetes-1:
            branches: main
        - node-image-publish-cloud-in-a-box-kubernetes-2:
            branches: main
        - node-image-publish-osism-1:
            branches: main
        - node-image-publish-osism-2:
            branches: main
        - node-image-publish-osism-3:
            branches: main
        - node-image-publish-osism-4:
            branches: main
    periodic-daily:
      jobs:
        - flake8
        - hadolint
        - python-black
        - yamllint
