---
- secret:
    name: SECRET_NODE_IMAGE
    data:
      MINIO_ACCESS_KEY: !encrypted/pkcs1-oaep
        - hYDmLN9GOsYF9kKM6LB96mMHaC1PN0HrRrIHIDFHq9HFUo2wL4np0xrc0eoxd4iZziqsu
          J1jJZkTU+vlZKn9viE0HXbCnmi9dqWI0toZYCw/olrZnR3EK0Ks8b1cGFwSW+w361UOPG
          eS5WQ4IAfvnav/FvubpB19H3Al8s215o3TYiwBejTNiQg4p5NI3Y9HxlUpGQden0ojJ3N
          Wv27AXFJ2f+8ITNtZo6UTylwy27euKcTgq0r98tJNYxrtnbqyuBCDO9bhBrtyusy4gSrv
          yOXbqhLAy08BH02W3BfDhf5MSlZpilkanrYZWpndaBX2iiQeDsigOLl8Xp0HnW8wNulAu
          Y1hng2LmM9vvvPNSNt80xJuOua6eY7q2pfP46dYvC0Ls28QdF8/HBwx8RV6Pn8Wu+XIiw
          7l4ByJZh8iGzQx4hrFRK5dW9ulVKk70Ll+so/NNMu5av5C3aBGjPr5jsa465U/+OUyB+V
          5g98qBqs3xq41qfp966CteYbvaYJItJtdgdGwZDXzouTYD0zAwq2RXicSIA2CSKbqKkuI
          IrtDxolpVQ3szhenZHjOsJpAKuMsxf9YX1tA8r+K2r5eqDFO1oATku/xiI/7GVMqxNlUC
          jrO+AI3TU4unGMbkCQXuxpZUZG71q3JA5AIx/LgXFvwzo+PAU34DW7ZaFVDvtY=
      MINIO_SECRET_KEY: !encrypted/pkcs1-oaep
        - Oj8wmmuZC6WRGP7Ut6BDYKIj6VZqfso+2ewK5MrgPpUKPK63Pb6nAThKlQscLiFVzON++
          AzEXGQN8vxX7HGvXwNdFn5C2z3+jIauTXbBPPR22pBbE/QQVjXfGV9TuaMhOhe2sKP7Yi
          ngZ9ABin2AsXC4YMt0unvEsqsdC73O774eA2J6BQOFYCwPjsPLeN2R89FDh55Nj0wZrlS
          v3QWuXQzwMbSrAMuEyTKPxXQdeVjkXxG1HkjF/1GTqpPaCIWQbQ4Okm6djbEdBTu94eKx
          nB35VQTjceiU+KPVrNbKz0JAB63Ysro3qmgZO5qc6OVCFa8KZIpH84LAh1dX4MiiCTZfS
          z9EXk2CjeThMfrIIT2vx0VdtUC1MX4zbe/Rj+zLmtXQwRNdoqF348yCnpmfv7DYxWrsyQ
          yllH0fmi8iClqE0S3+SF3jM1Cj4rtbV6uXy0b6aaFMvbt2kM1/BaL/c/3pwN/Xlu62Wy0
          iCkJT8l1I/zYDaZlFzK04QsNWjtXmKBzh4ymCWoA4WveMxSmrnpWCTjqZ2jQqreeaTZCZ
          DS7X5cWBbvTYN7JDrOCyEHzoJGP1ehf9Xh6nSDFvazIbVJatw1SEHZMq7I5thFTpsbu2E
          fFriHuZ8zLGIYP4QcLDWRPP0S1m6K2mpfg4jXs1BkHRxS6wsuWu0N0LRpJD+Ds=

- job:
    name: node-image-build
    abstract: true
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800
    vars:
      upload_image: false

- job:
    name: node-image-build-1
    parent: node-image-build
    vars:
      variant: 1
      description: 'Two mirrored SCSI disks with an enhanced set of predefined logical volumes'

- job:
    name: node-image-build-2
    parent: node-image-build
    vars:
      variant: 2
      description: 'Two mirrored SCSI disks with a single logical rootfs volume'

- job:
    name: node-image-build-3
    parent: node-image-build
    vars:
      variant: 3
      description: 'A single SCSI disk with a single logical rootfs volume'

- job:
    name: node-image-build-4
    parent: node-image-build
    vars:
      variant: 4
      description: 'A single NVMe disk with a single logical rootfs volume (/dev/nvme0n1)'

- job:
    name: node-image-build-cloud-in-a-box-1
    parent: node-image-build
    vars:
      variant: cloud-in-a-box-1
      description: 'A Cloud in a Box image for a single SCSI disk with a single logical rootfs volume'

- job:
    name: node-image-build-cloud-in-a-box-2
    parent: node-image-build
    vars:
      variant: cloud-in-a-box-2
      description: 'A Cloud in a Box image for a single NVMe disk with a single logical rootfs volume'

- job:
    name: node-image-build-cloud-in-a-box-edge-2
    parent: node-image-build
    vars:
      variant: cloud-in-a-box-edge-2
      description: 'A Cloud in a Box edge image for a single NVMe disk with a single logical rootfs volume'

- job:
    name: node-image-build-cloud-in-a-box-kubernetes-1
    parent: node-image-build
    vars:
      variant: cloud-in-a-box-kubernetes-1
      description: 'A Cloud in a Box image with Kubernetes for a single SCSI disk with a single logical rootfs volume'

- job:
    name: node-image-build-cloud-in-a-box-kubernetes-2
    parent: node-image-build
    vars:
      variant: cloud-in-a-box-kubernetes-2
      description: 'A Cloud in a Box image with Kubernetes for a single NVMe disk with a single logical rootfs volume'

- job:
    name: node-image-build-cloud-in-a-box-ironic-1
    parent: node-image-build
    vars:
      variant: cloud-in-a-box-ironic-1
      description: 'A Cloud in a Box image with Ironic for a single SCSI disk with a single logical rootfs volume'

- job:
    name: node-image-build-cloud-in-a-box-ironic-2
    parent: node-image-build
    vars:
      variant: cloud-in-a-box-ironic-2
      description: 'A Cloud in a Box image with Ironic for a single NVMe disk with a single logical rootfs volume'

- job:
    name: node-image-build-osism-1
    parent: node-image-build
    vars:
      variant: osism-1
      description: 'Two mirrored NVMe disks with a single logical rootfs volume (/dev/nvme3n1 and /dev/nvme4n1)'
      layer3_underlay: true

- job:
    name: node-image-build-osism-2
    parent: node-image-build
    vars:
      variant: osism-2
      description: 'Two mirrored NVMe disks with a single logical rootfs volume (/dev/nvme4n1 and /dev/nvme5n1)'
      layer3_underlay: true

- job:
    name: node-image-build-osism-3
    parent: node-image-build
    vars:
      variant: osism-3
      description: 'Two mirrored NVMe disks with a single logical rootfs volume (/dev/nvme2n1 and /dev/nvme3n1)'
      layer3_underlay: true

- job:
    name: node-image-build-osism-4
    parent: node-image-build
    vars:
      variant: osism-4
      description: 'Two mirrored NVMe disks with a single logical rootfs volume (/dev/nvme0n1 and /dev/nvme1n1)'
      layer3_underlay: true

- job:
    name: node-image-publish-1
    parent: node-image-build-1
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-2
    parent: node-image-build-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-3
    parent: node-image-build-3
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-4
    parent: node-image-build-4
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-1
    parent: node-image-build-cloud-in-a-box-1
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-2
    parent: node-image-build-cloud-in-a-box-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-edge-2
    parent: node-image-build-cloud-in-a-box-edge-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-kubernetes-1
    parent: node-image-build-cloud-in-a-box-kubernetes-1
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-kubernetes-2
    parent: node-image-build-cloud-in-a-box-kubernetes-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-ironic-1
    parent: node-image-build-cloud-in-a-box-ironic-1
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-ironic-2
    parent: node-image-build-cloud-in-a-box-ironic-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-osism-1
    parent: node-image-build-osism-1
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-osism-2
    parent: node-image-build-osism-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-osism-3
    parent: node-image-build-osism-3
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-osism-4
    parent: node-image-build-osism-4
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - flake8
        - python-black
        - yamllint
    label:
      jobs:
        - node-image-build-1
        - node-image-build-2
        - node-image-build-3
        - node-image-build-4
        - node-image-build-cloud-in-a-box-1
        - node-image-build-cloud-in-a-box-2
        - node-image-build-cloud-in-a-box-edge-2
        - node-image-build-cloud-in-a-box-kubernetes-1
        - node-image-build-cloud-in-a-box-kubernetes-2
        - node-image-build-cloud-in-a-box-ironic-1
        - node-image-build-cloud-in-a-box-ironic-2
        - node-image-build-osism-1
        - node-image-build-osism-2
        - node-image-build-osism-3
        - node-image-build-osism-4
    post:
      jobs:
        - node-image-publish-1:
            branches: main
        - node-image-publish-2:
            branches: main
        - node-image-publish-3:
            branches: main
        - node-image-publish-4:
            branches: main
        - node-image-publish-cloud-in-a-box-1:
            branches: main
        - node-image-publish-cloud-in-a-box-2:
            branches: main
        - node-image-publish-cloud-in-a-box-edge-2:
            branches: main
        - node-image-publish-cloud-in-a-box-kubernetes-1:
            branches: main
        - node-image-publish-cloud-in-a-box-kubernetes-2:
            branches: main
        - node-image-publish-cloud-in-a-box-ironic-1:
            branches: main
        - node-image-publish-cloud-in-a-box-ironic-2:
            branches: main
        - node-image-publish-osism-1:
            branches: main
        - node-image-publish-osism-2:
            branches: main
        - node-image-publish-osism-3:
            branches: main
        - node-image-publish-osism-4:
            branches: main
    periodic-daily:
      jobs:
        - flake8
        - python-black
        - yamllint
