---
- secret:
    name: SECRET_NODE_IMAGE
    data:
      MINIO_ACCESS_KEY: !encrypted/pkcs1-oaep
        - CTogCx39HadGnkbi45DheqCctn3MqB+P0v3OPeFklMjJxQ5zc7Glhb30SUM+VQMHWABtC
          DLGUNvfj+hAqH0lWSdCbhT1nvoIcAgzEUZmTz9PX+ExMQV+OaMg9Lub5nlBuVSYUcCmuV
          l2dy33znml22ZgVKhH1Db57sPSMSJOFN9Cb6oqZ8csJSVi/9CU2fXpiQwT2HatMsUQixk
          XQbUTIHGyWQuyBGOMiTC75z2Ci2f8QY9X+aLTkLPFr4EyigzvsYP4sDwnFqUDV85tEFVt
          RE9g8hRORZUToH1qkLh+hMbHM1WjDM1qa2rIJId5eoSbWf5HSuUHr69XXGZN3HYMObDDZ
          E8upB5EFjajqNbWGR4f7m6e0H1dzoXRMzgHcSfgmWQzryrQ5rHIG3h6aEwLeJgItLoYP8
          9HJJlxX3xrHEHJxVNBEINf66EBW1wwDgT1NtZZSZTYbHKJ7W9dKxZAQREEv+O5fxryeZI
          gTYBgweYtC91rCed1UeslT/At0/NAw6dt7RNc80/uwpZMDjzvx7K1pHWESKwgFoAukBcm
          vGZcIjLNY8FLA7Zurz6JZoykcJzJ9DFA/WX7D3ssEvrwUKg6ke8tinXxTkrLmUQIU52tD
          9e04c3AMsm5sL/rtIMmD+3Vy6nQo/nxE2+MdsOyXMzVfjN9k8fwUvg9OfDF7UI=
      MINIO_SECRET_KEY: !encrypted/pkcs1-oaep
        - UG90Ml5NT4w76t0K6HdHXy9rnVJg77/VqtyRzEqePozxixjs9m2ILZxVxtIJ1GKLQss56
          wMxs4froxgpf/2H82zEuU1JCIWOEUVNuX4ta09/FDKXWTRBl9kG4y3SG3rbzKqdRnGu21
          771+vIR7LJrAaXyEpTi30BvsbsAFpITTkm9s57IRZprFRYZtkzg9GpzisU+s/w7sFiJlc
          HJCprbBqsmcMcRfEvAabG7d4y5qLMbtz+4amkoHv0kv7yiGhH80GZXl4x0lp/5xG5MCyv
          X8LxRPoWRFjVLGZ8LrTWMUVWrD/VTP3cLxfzWuL+q8FRn5/CgZeeaZtKxjzBwKnrpf7R8
          QzN4LFj3G0rWGTtc5YQlRtfhfJgpivI6xxclxneBCNPFR8RtXYKEUrSyqcgOsEeQ2DDfk
          tRl/VnivtZEA96ijQNjWhrY0QOGVO+NAlHQRNLWZL9O0fF6o+m9mnI5PxmSoRfVYHhypw
          gvB8/nzpuy6Nw9WLwsYqcwh+Lh/AYYj2PbtFTaI1XzTG5xbHphUWIXsPoOhqVnFQEzp4c
          Gx9EgRUgCW05HhW6AUuMz8czk8o9k3mRfMrxUdPsapZP2POTZQTjas6z65KvCKdnxafT5
          DOJcWgNbzeU0aTwbhFTuUsbvAz0WuWDVIz7IPi9Ka6lJgIrLw/kh4Gu2no99mU=

- job:
    name: node-image-build
    abstract: true
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    timeout: 1800
    vars:
      upload_image: false

- job:
    name: node-image-build-cloud-in-a-box-1
    parent: node-image-build
    vars:
      name: cloud-in-a-box-1

- job:
    name: node-image-build-cloud-in-a-box-2
    parent: node-image-build
    vars:
      name: cloud-in-a-box-2

- job:
    name: node-image-build-osism-1
    parent: node-image-build
    vars:
      name: osism-1

- job:
    name: node-image-build-osism-2
    parent: node-image-build
    vars:
      name: osism-2

- job:
    name: node-image-build-osism-3
    parent: node-image-build
    vars:
      name: osism-3

- job:
    name: node-image-build-osism-4
    parent: node-image-build
    vars:
      name: osism-4

- job:
    name: node-image-publish-cloud-in-a-box-1
    parent: node-image-build-cloud-in-a-box-1
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-cloud-in-a-box-2
    parent: node-image-build-cloud-in-a-box-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-osism-1
    parent: node-image-build-osism-1
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-osism-2
    parent: node-image-build-osism-2
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-osism-3
    parent: node-image-build-osism-3
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- job:
    name: node-image-publish-osism-4
    parent: node-image-build-osism-4
    vars:
      upload_image: true
    secrets:
      - name: minio
        secret: SECRET_NODE_IMAGE
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - node-image-build-cloud-in-a-box-1
        - node-image-build-cloud-in-a-box-2
        - node-image-build-osism-1
        - node-image-build-osism-2
        - node-image-build-osism-3
        - node-image-build-osism-4
        - yamllint
    post:
      jobs:
        - node-image-publish-cloud-in-a-box-1:
            branches: main
        - node-image-publish-cloud-in-a-box-2:
            branches: main
        - node-image-publish-osism-1:
            branches: main
        - node-image-publish-osism-2:
            branches: main
        - node-image-publish-osism-3:
            branches: main
        - node-image-publish-osism-4:
            branches: main
    periodic-daily:
      jobs:
        - yamllint
