# SPDX-License-Identifier: Apache-2.0
---
- name: Build image
  hosts: all

  vars:
    name: "{{ variant | default('cloud-in-a-box-1') }}"

  tasks:
    - name: Prepare build environment
      ansible.builtin.command:
        chdir: "{{ zuul.project.src_dir }}"
        cmd: bash create-image.sh --env

    - name: Run build script
      ansible.builtin.command:
        chdir: "{{ zuul.project.src_dir }}"
        cmd: bash create-image.sh -b node-image-build-{{ name }}

    - name: Run upload script
      ansible.builtin.shell:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
        cmd: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set minio https://nbg1.your-objectstorage.com {{ minio.MINIO_ACCESS_KEY | trim }} {{ minio.MINIO_SECRET_KEY | trim }} --api "s3v4"
          ./mc cp ubuntu-autoinstall-{{ name }}.iso minio/osism/node-image/
          ./mc cp ubuntu-autoinstall-{{ name }}.iso.CHECKSUM minio/osism/node-image/
      when: upload_image|bool
      no_log: true
