name: Build image
on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - user-data
      - image-create.sh
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install required packages
        run: sudo apt-get install --yes xorriso sed curl gpg wget fdisk isolinux
      - name: Build image
        run: |
          bash image-create.sh -r -a -k -u user-data -n jammy
      - name: Upload image
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set minio https://minio.services.osism.tech ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}
          ./mc cp ubuntu-autoinstall.iso minio/node-image
          ./mc policy set download minio/node-image/ubuntu-autoinstall.iso
        if: github.ref == 'refs/heads/main'
