name: Build image
on:
  push:
    branches: [ "main" ]
jobs:
  build-image:
    runs-on: ubuntu-latest
    container: 
      image: deserializeme/pxeless:latest
      options: -v ${{ github.workspace }}:/data
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          /app/image-create.sh -a -k -u /data/user-data -n jammy
      - name: Upload image
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set minio https://minio.services.osism.tech ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}
          ./mc cp ubuntu-autoinstall.iso minio/node-image
          ./mc policy set download minio/node-image/ubuntu-autoinstall.iso
        if: github.ref == 'refs/heads/main'
